// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using covid.Services;

namespace covid.Migrations
{
    [DbContext(typeof(CaseDBContext))]
    [Migration("20201116215449_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("covid.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description",
                            FirstName = "John",
                            LastName = "Doe",
                            Type = "Cured"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description",
                            FirstName = "Jill",
                            LastName = "Doe",
                            Type = "Cured"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description",
                            FirstName = "Amy",
                            LastName = "Doe",
                            Type = "Infected"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description",
                            FirstName = "Steve",
                            LastName = "Doe",
                            Type = "Cured"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description",
                            FirstName = "Amy",
                            LastName = "House",
                            Type = "Infected"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description",
                            FirstName = "Sam",
                            LastName = "Wood",
                            Type = "Deceased"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description",
                            FirstName = "Alex",
                            LastName = "Clay",
                            Type = "Deceased"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
